== Formål, omfang og avgrensinger [[Formål_omfang_og_avgrensinger]]

https://data.norge.no/specification/spesifikasjon-for-beskrivelse-av-kvalitet-pa-datasett/[__Spesifikasjon for beskrivelse av kvalitet på datasett__ &#x29C9;, window="_blank", role="ext-link"] foreslo å bruke https://www.w3.org/TR/vocab-dqv/[__DQV (Data Quality Vocabulary)__ fra W3C &#x29C9;, window="_blank", role="ext-link"] til å beskrive kvalitet på datasett i https://data.norge.no/about[Felles datakatalog &#x29C9;, window="_blank", role="ext-link"]. 

Dette er en teknisk spesifikasjon for en norsk applikasjonsprofil av DQV, DQV-AP-NO. DQV-AP-NO er ikke en direkte oversettelse av DQV fra W3C. I tillegg til å beskrive hvordan klasser og egenskaper i DQV brukes, tilpasses DQV til norske forhold ved å bruke norske utvidelser i denne applikasjonsprofilen.

Applikasjonsprofilen inngår i https://www.digdir.no/informasjonsforvaltning/rammeverk-informasjonsforvaltning/2118[Rammeverk for informasjonsforvaltning &#x29C9;, window="_blank", role="ext-link"]. Den brukes sammen med og supplerer https://data.norge.no/specification/dcat-ap-no/[DCAT-AP-NO &#x29C9;, window="_blank", role="ext-link"].

Applikasjonsprofilen tar utgangspunkt i datasett (`dcat:Dataset`) som det skal beskrives kvalitet for. Den kan også på tilsvarende måte brukes til å beskrive kvalitet på bl.a. en distribusjon (`dcat:Distribution`), uten at dette eksplisitt beskrives i denne spesifikasjonen.
