name: build adocs and publish v1 to production

permissions:
  contents: read

on:
  push:
    branches:
      - v1
    paths:
      - docs/**
  workflow_dispatch:

jobs:
  upload-files-to-production:
    name: Upload specification to static-rdf-server
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-upload-files.yaml@main
    with:
      ref: v1
      program_html: |
        asciidoctor -D docs -o index.html -a lang=nb docs/main.adoc
      program_pdf: |
        asciidoctor-pdf -D docs -o files/dqv-ap-no.pdf -a lang=nb docs/main.adoc
      program_pdf_continue_on_error: true
      host: https://data.norge.no
      ontology: dqv-ap-no
      ontology-type: specification
      files: |
        docs/index.html text/html nb
        docs/files/dqv-ap-no.pdf application/pdf nb files/dqv-ap-no.pdf
        docs/images/Digdir.png image/png nb images/Digdir.png
        docs/images/dqv-ap-no.png image/png nb images/dqv-ap-no.png
    secrets:
      STATIC_RDF_SERVER_API_KEY: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}
